### ISSUE TITLE
ui not responsive

### ISSUE THREAD

**Issue by mahendrarathore1742** [JoseDeFreitas/thisisme#21]
it's not mobile responsive

**Comment by JoseDeFreitas** [comment]
Hello! You're right. The page is not mobile responsive, but when the layout and positioning systems are correct the style will be responsive for different screen sizes. I may keep this open for now if someone wants to make a comment. Thank you for opening this!

**Comment by JoseDeFreitas** [comment]
I'm closing this issue because it is already mobile responsive in the dev branch.
