### ISSUE TITLE
Result  Nav not aligned

### ISSUE THREAD

**Issue by manthony9** [JoseDeFreitas/thisisme#24]
**Describe the bug**
Clicking on the Result button on the nav moves the entire nav bar to the center/left of the screen. This does not happen for 
other nav options.

**To Reproduce**
1. Click on the Result option moves the bar to the right

**Expected behavior**
1. Nav bar should stay where it is.

**Screenshots**

**Desktop or Smartphone (please complete the following information):**
-Desktop

**Additional context**
I'm not sure if this is a part of the design or a bug.

**Comment by JoseDeFreitas** [comment]
Hello! It was a problem the design had, but now it's fixed.
Commits that fixed this issue: 01ac124dce34f6033b8362c4a613fa866053957e and b7c4d0ead5e45a4de46d2115c1756acd2fa18843.
Because of this, I'll close this issue. Thank you for opening it 😉.
