### ISSUE TITLE
Add system to save SVG images from the website

### ISSUE THREAD

**Issue by JoseDeFreitas** [JoseDeFreitas/thisisme#4]
_To know what I mean, go to the website [thisisme.vercel.app](https://thisisme.vercel.app) (which is the website of the application.) That build if from the last commit made._

I want the user to be able to download the SVG image they've created (the one that wraps all images up, in the Result section.) There should be a button that gives you the `.svg` file. Look into the [pages folder](https://github.com/JoseDeFreitas/thisisme/tree/main/src/pages).
If you want to work on it, mention me and I'll assign you. The PR you create will be reviewed.

**Mention me if you need more information**. Thanks in advance! 😄

**Comment by therohitdas** [comment]
I want to work on this but I don't understand how this app works. See #8

**Comment by chris--jones** [comment]
I made an attempt of this in pr #10 
I encountered a lot of display issues with the layout, both the html/css and the svg - so I'll offer some assistance there as well.

**Comment by JoseDeFreitas** [comment]
Hello!

@therohitdas thank you! I've already sent a comment on the issue you've created (#8) explaining what this web app is about, how to use it, and the future guides to how to use it. If you still want to work on this tell me so that I can assign you. Thank you and sorry for the repository for not being descriptive enough (or _at all_ I should say 😅.)

@chris--jones I've reviewed your PRs! Thank you a lot for that. And sorry for that, as I said in the issues I've created the code is not effective (it works, but it's hard to understand and it will probably break when trying to do something else). If you want to work optimizing that I would be thankful! I've already assigned you to this issue.

If you have something to tell me, whatever, just mention me in this issue. Thank you both a lot!

**Comment by theniteshnarang** [comment]
I liked the project, I want to contribute in it please assign me some issue.

**Comment by JoseDeFreitas** [comment]
Hello @theniteshnarang! Thank you. This issue is completed I guess. It's opened to receive some possible comments about and improvement, but I think it's really great. The issues #2, #3, and #14 are opened for contribution. They already have people assigned, but you can also help. Don't limit only to this though. If you want you can navigate through the website and find something you can improve (or in the code I made, which looks very strange at this moment.) Tell me whatever you want to work on and I'll create an issue about it and assign you (or just assign you to the PR you make.) Thank you for your interest!

**Comment by chris--jones** [comment]
The saving code works by grabbing the contents of the svg element, so it's unlikely to break with other code changes - although some consideration will need to be made to the dimensions as the height and width are fixed right now and will need to be dynamic (e.g. for optional sections).

I also noticed an svg library was included in the package.json (svg.js), but is presently unused. With this library the only difference in rendering to file would be using svg.draw() to output the svg string.

**Comment by theniteshnarang** [comment]
> Hello @theniteshnarang! Thank you. This issue is completed I guess. It's opened to receive some possible comments about and improvement, but I think it's really great. The issues #2, #3, and #14 are opened for contribution. They already have people assigned, but you can also help. Don't limit only to this though. If you want you can navigate through the website and find something you can improve (or in the code I made, which looks very strange at this moment.) Tell me whatever you want to work on and I'll create an issue about it and assign you (or just assign you to the PR you make.) Thank you for your interest!

Hello @JoseDeFreitas , I want to start on the project by working on README.md file, is it ok for you? If it is then lemme know what major Sections you want in the README.md OR any Specific details.

**Comment by JoseDeFreitas** [comment]
@chris--jones yes, that's something that needs a fix. As you may notice, the "Result" section shows what looks like only one image, but in fact, all images you generate in the other sections (at this moment only Programming and Technologies) are there, but one above each other. The images are taken from the localStorage so I don't know how to add parameters to set them a different x and y values to show them one next to the other and below the other (up to 2 in a row, something like 2 x 6).

About the library, I added it some time ago because I thought I needed it, but I managed to do it without it. Maybe that's the solution to this positioning problem, but the library will stay there until everything is working as expected. If there's no use I'll remove it.

**Comment by JoseDeFreitas** [comment]
@theniteshnarang a user has taken the README file hours ago (issue #8). But, if you want to, you can make some tutorials on the page itself (like the notes that are below the forms.) If you have any other ideas just tell me without problems.

**Comment by chris--jones** [comment]
@JoseDeFreitas - My svg is a bit rusty, but I think the positioning should be applied to group tags (<g>) surrounding each section.

If I were you though, I would refactor this to instead create and maintain a simple data model in local storage and have the svg rendering logic completely separate as it'll make it far easier to do positioning and make layout and styling changes in one place rather than have to dig into individual pages to correct the svg. Basically separate your data and rendering concerns.

**Comment by JoseDeFreitas** [comment]
@chris--jones yes, that would be the best way to do it. There will be a problem with those other issues, so I agree with waiting a little bit to see how does that works. But, if you would want to work on refactoring the code, you can start that and keep it there until the other things are completed. Let me know any other thing 🙂.

**Comment by JoseDeFreitas** [comment]
Hello! There have been some important changes recently. These should not break what you're doing, but it's important that you pull them. Please see the [latest Pull requests](https://github.com/JoseDeFreitas/thisisme/pulls) (both closed and opened.) Let me know anything. Thank you!

**Comment by chris--jones** [comment]
Hi @JoseDeFreitas - I don't think there's anything left to do for this issue...

**Comment by JoseDeFreitas** [comment]
Hello @chris--jones! You're right. The system to save the images is very good. I'll be closing this issue. Thank you.
