### ISSUE TITLE
Add a how to use section.

### ISSUE THREAD

**Issue by therohitdas** [JoseDeFreitas/thisisme#8]
**Is your feature request related to a problem? Please describe.**
I was trying to understand how to use this website. A clear **Read Me** or a page with step by step instruction can help a user understand this project better.

**Describe the solution you'd like**
Create a Read Me or a Page to describe - "How to use this app."

**Describe alternatives you've considered**
I tried hacking around. Clicking buttons and filling inputs. Not recommended.

**Additional context**
None

**Comment by JoseDeFreitas** [comment]
Hello @therohitdas!

_First of all, the latest version **is not** the one that is on the repository website ([thisisme](https://thisisme.vercel.app)); you can find the latest version by cloning the repository and running `npm start`. I know this may be something annoying, but when the new version comes out it will be available in the link deployed in the production stage. Sorry for this._

This web app is used to create images that you can then put on your GitHub Readme. The web app consists of some sections. Each of these sections contains the inputs to form one card (one section is Programming, other is Technologies, etc.) The text you type in the inputs are stored in the localStorage and then that value is used in the image. The images keep saved when you change page or refresh the entire web app. Each section contains a different image you can generate through the inputs. If you don't type anything, the image will not count and will not be displayed later in the big image from the "Result" section.
There's the "Result" section. In that section, all images from the previous sections are mixed and set on one big image (by taking the previous images you've generated. This big image only shows the images you've put some text in it, through the inputs in the corresponding sections. The images that you don't fill up will not be shown.) Then, you are able to download this image and to put it on your GitHub Readme.
Overall, to use it just fill up the forms **you want** to add that information to an image. The images that you generate through the forms will be displayed in every section in the right-hand side of the form and then, in the "Result" section, all images will appear and you will be able to download that image, with the main purpose of using it on your GitHub Readme.

About the guides, you're totally right. As I'm still working on this I haven't written any guides yet. I want to have a brief but concise description of how to use it in the [readme file](https://github.com/JoseDeFreitas/thisisme#readme), though a page in the actual website (web app) could be also good. Thank you for this recommendation.
You've commented on the #4 issue. There's already a person working on it, but I think you can also help contribute. I've also sent you a message on that issue (if you haven't read it already.) If you don't want to contribute to that or you find the solution good enough, you can help me creating those guidelines you're telling me (I can also help you with that.) If you want to work on that issue it's also good; tell me so I can assign you to it.

Last, sorry about the situation. I didn't set up this  a good way (I think.) Writing of the code, the thing I did is not optimized at all 😅. I'll keep this open for discussion. Thank you a lot!

**Comment by therohitdas** [comment]
Hi @JoseDeFreitas 

Thanks for this long comment.
I now understand how this website works.

I believe we should first create a README.md file [ Please leave it to me. ]

I will install this project later today and hack around to see what can be improve or requires more work.

It will be fun.

Just wanted to ask: Are you still using discord? So I will be able to better communicate with you there.

**Comment by JoseDeFreitas** [comment]
Hello @therohitdas! Thank you a lot for that. Okay, I just assigned you to this issue 👍. And yes, I use Discord every day. My username and tag are **Jose#7947**. Thank you!

**Comment by JoseDeFreitas** [comment]
The Pull requests of the README file (#16 and #17) have been reviewed, accepted, and merged. Because of this, I'll close this issue. This work is done, the explanation in the README file is great so the web app doesn't need to have a separate section for explanations (at least for now.) Thank you for making the README file and for contributing! 🤗
